Repository brain-tec/social, pull requests merged in 2020-08, with the labels that each got.

#347 Syncing from upstream OCA/social (12.0)
  mail_debrand/i18n/fr_CH.po
  mass_mailing_list_dynamic/__manifest__.py
  mass_mailing_list_dynamic/models/mail_mass_mailing_contact.py
Labels: 12.0

#348 Syncing from upstream OCA/social (12.0)
  mail_debrand/i18n/fr.po
  mail_debrand/i18n/fr_CH.po
Labels: 12.0

#349 Syncing from upstream OCA/social (12.0)
  mail_restrict_follower_selection/__manifest__.py
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
Labels: 12.0

#351 Syncing from upstream OCA/social (12.0)
  mail_activity_board/i18n/pt.po
  mail_activity_team/i18n/pt.po
Labels: 12.0

#352 Syncing from upstream OCA/social (12.0)
  fetchmail_thread_default/i18n/sl.po
Labels: 12.0

#353 Syncing from upstream OCA/social (12.0)
  README.md
  mass_mailing_partner/i18n/fi.po
Labels: 12.0

#354 Syncing from upstream OCA/social (13.0)
  README.md
  mail_debrand/i18n/fr.po
Labels: 13.0

#355 Syncing from upstream OCA/social (11.0)
  mail_activity_done/i18n/de.po
Labels: 11.0

#356 Syncing from upstream OCA/social (12.0)
  base_search_mail_content/i18n/de.po
  base_search_mail_content/i18n/fr.po
  mail_activity_team/i18n/da.po
  mail_tracking/i18n/ca.po
  mail_tracking/i18n/de.po
  mail_tracking/i18n/es.po
  mail_tracking/i18n/es_CO.po
  mail_tracking/i18n/fi.po
  mail_tracking/i18n/fr.po
  mail_tracking/i18n/hr.po
  mail_tracking/i18n/it.po
  mail_tracking/i18n/nb.po
  mail_tracking/i18n/nl.po
  mail_tracking/i18n/nl_NL.po
  mail_tracking/i18n/pt.po
  mail_tracking/i18n/pt_BR.po
  mail_tracking/i18n/tr.po
  mail_tracking/i18n/tr_TR.po
  mass_mailing_custom_unsubscribe/i18n/de.po
  mass_mailing_custom_unsubscribe/i18n/es.po
  mass_mailing_custom_unsubscribe/i18n/fr.po
  mass_mailing_custom_unsubscribe/i18n/it.po
  mass_mailing_custom_unsubscribe/i18n/sl.po
  mass_mailing_event_registration_exclude/i18n/es.po
Labels: 12.0

#357 Syncing from upstream OCA/social (13.0)
  base_search_mail_content/i18n/de.po
  base_search_mail_content/i18n/fr.po
  email_template_qweb/i18n/de.po
  email_template_qweb/i18n/es.po
  email_template_qweb/i18n/es_MX.po
  email_template_qweb/i18n/fr.po
  email_template_qweb/i18n/hr.po
  email_template_qweb/i18n/it.po
  email_template_qweb/i18n/pt_BR.po
  mail_tracking/i18n/ca.po
  mail_tracking/i18n/de.po
  mail_tracking/i18n/es.po
  mail_tracking/i18n/es_CO.po
  mail_tracking/i18n/fi.po
  mail_tracking/i18n/fr.po
  mail_tracking/i18n/hr.po
  mail_tracking/i18n/it.po
  mail_tracking/i18n/nb.po
  mail_tracking/i18n/nl.po
  mail_tracking/i18n/nl_NL.po
  mail_tracking/i18n/pt.po
  mail_tracking/i18n/pt_BR.po
  mail_tracking/i18n/sl.po
  mail_tracking/i18n/tr.po
  mail_tracking/i18n/tr_TR.po
  mail_tracking_mailgun/i18n/es.po
  mail_tracking_mailgun/i18n/hr.po
  mail_tracking_mailgun/i18n/it.po
  mail_tracking_mailgun/i18n/nl_NL.po
  mail_tracking_mass_mailing/i18n/ca.po
  mail_tracking_mass_mailing/i18n/de.po
  mail_tracking_mass_mailing/i18n/es.po
  mail_tracking_mass_mailing/i18n/fi.po
  mail_tracking_mass_mailing/i18n/fr.po
  mail_tracking_mass_mailing/i18n/hr.po
  mail_tracking_mass_mailing/i18n/it.po
  mail_tracking_mass_mailing/i18n/pt.po
  mail_tracking_mass_mailing/i18n/sl.po
  mass_mailing_list_dynamic/i18n/ca.po
  mass_mailing_list_dynamic/i18n/de.po
  mass_mailing_list_dynamic/i18n/es.po
  mass_mailing_list_dynamic/i18n/fr.po
  mass_mailing_list_dynamic/i18n/hr.po
  mass_mailing_list_dynamic/i18n/it.po
  mass_mailing_list_dynamic/i18n/pt.po
  mass_mailing_list_dynamic/i18n/sl.po
  mass_mailing_partner/i18n/ca.po
  mass_mailing_partner/i18n/de.po
  mass_mailing_partner/i18n/es.po
  mass_mailing_partner/i18n/fr.po
  mass_mailing_partner/i18n/hr.po
  mass_mailing_partner/i18n/it.po
  mass_mailing_partner/i18n/pt.po
  mass_mailing_partner/i18n/sl.po
Labels: 13.0

#359 Syncing from upstream OCA/social (12.0)
  README.md
  test_mail_private/__manifest__.py
Labels: 12.0

#360 Update 20200825 updating from braintec fork for version 13
  README.md
  base_search_mail_content/i18n/de.po
  base_search_mail_content/i18n/fr.po
  email_template_qweb/i18n/de.po
  email_template_qweb/i18n/es.po
  email_template_qweb/i18n/es_MX.po
  email_template_qweb/i18n/fr.po
  email_template_qweb/i18n/hr.po
  email_template_qweb/i18n/it.po
  email_template_qweb/i18n/pt_BR.po
  mail_debrand/i18n/fr.po
  mail_tracking/i18n/ca.po
  mail_tracking/i18n/de.po
  mail_tracking/i18n/es.po
  mail_tracking/i18n/es_CO.po
  mail_tracking/i18n/fi.po
  mail_tracking/i18n/fr.po
  mail_tracking/i18n/hr.po
  mail_tracking/i18n/it.po
  mail_tracking/i18n/nb.po
  mail_tracking/i18n/nl.po
  mail_tracking/i18n/nl_NL.po
  mail_tracking/i18n/pt.po
  mail_tracking/i18n/pt_BR.po
  mail_tracking/i18n/sl.po
  mail_tracking/i18n/tr.po
  mail_tracking/i18n/tr_TR.po
  mail_tracking_mailgun/i18n/es.po
  mail_tracking_mailgun/i18n/hr.po
  mail_tracking_mailgun/i18n/it.po
  mail_tracking_mailgun/i18n/nl_NL.po
  mail_tracking_mass_mailing/i18n/ca.po
  mail_tracking_mass_mailing/i18n/de.po
  mail_tracking_mass_mailing/i18n/es.po
  mail_tracking_mass_mailing/i18n/fi.po
  mail_tracking_mass_mailing/i18n/fr.po
  mail_tracking_mass_mailing/i18n/hr.po
  mail_tracking_mass_mailing/i18n/it.po
  mail_tracking_mass_mailing/i18n/pt.po
  mail_tracking_mass_mailing/i18n/sl.po
  mass_mailing_list_dynamic/i18n/ca.po
  mass_mailing_list_dynamic/i18n/de.po
  mass_mailing_list_dynamic/i18n/es.po
  mass_mailing_list_dynamic/i18n/fr.po
  mass_mailing_list_dynamic/i18n/hr.po
  mass_mailing_list_dynamic/i18n/it.po
  mass_mailing_list_dynamic/i18n/pt.po
  mass_mailing_list_dynamic/i18n/sl.po
  mass_mailing_partner/i18n/ca.po
  mass_mailing_partner/i18n/de.po
  mass_mailing_partner/i18n/es.po
  mass_mailing_partner/i18n/fr.po
  mass_mailing_partner/i18n/hr.po
  mass_mailing_partner/i18n/it.po
  mass_mailing_partner/i18n/pt.po
  mass_mailing_partner/i18n/sl.po
Labels: 13.0.project_mi_465

#361 Syncing from upstream OCA/social (13.0)
  base_search_mail_content/i18n/fr.po
Labels: 13.0

#362 Syncing from upstream OCA/social (12.0)
  README.md
  mail_debrand/i18n/id.po
  mail_history/README.rst
  mail_history/__init__.py
  mail_history/__manifest__.py
  mail_history/hooks.py
  mail_history/i18n/mail_history.pot
  mail_history/models/__init__.py
  mail_history/models/mail_message.py
  mail_history/models/mail_notification.py
  mail_history/readme/CONFIGURE.rst
  mail_history/readme/CONTRIBUTORS.rst
  mail_history/readme/DESCRIPTION.rst
  mail_history/readme/INSTALL.rst
  mail_history/readme/ROADMAP.rst
  mail_history/readme/USAGE.rst
  mail_history/static/description/icon.png
  mail_history/static/description/index.html
  mail_history/static/src/js/discuss.js
  mail_history/static/src/js/mail_manager.js
  mail_history/static/src/js/mailbox.js
  mail_history/static/src/js/message.js
  mail_history/static/src/xml/discuss.xml
  mail_history/static/src/xml/thread.xml
  mail_history/views/assets.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mail_history/odoo/addons/mail_history
  setup/mail_history/setup.py
Labels: 12.0

#365 Syncing from upstream OCA/social (13.0)
  README.md
  mail_activity_done/__manifest__.py
  mail_activity_done/static/src/js/mail_activity.js
  mass_mailing_custom_unsubscribe/__manifest__.py
  mass_mailing_custom_unsubscribe/static/src/js/contact.tour.js
  mass_mailing_custom_unsubscribe/static/src/js/partner.tour.js
Labels: 13.0
