Repository brain-tec/social, pull requests merged in 2022-05, with the labels that each got.

#600 Syncing from upstream OCA/social (14.0)
  README.md
  mail_restrict_follower_selection/README.rst
  mail_restrict_follower_selection/__init__.py
  mail_restrict_follower_selection/__manifest__.py
  mail_restrict_follower_selection/data/ir_actions.xml
  mail_restrict_follower_selection/data/ir_config_parameter.xml
  mail_restrict_follower_selection/i18n/de.po
  mail_restrict_follower_selection/i18n/en.po
  mail_restrict_follower_selection/i18n/fr.po
  mail_restrict_follower_selection/i18n/hr.po
  mail_restrict_follower_selection/i18n/it.po
  mail_restrict_follower_selection/i18n/mail_restrict_follower_selection.pot
  mail_restrict_follower_selection/i18n/sl.po
  mail_restrict_follower_selection/models/__init__.py
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_thread.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
  mail_restrict_follower_selection/readme/CONFIGURE.rst
  mail_restrict_follower_selection/readme/CONTRIBUTORS.rst
  mail_restrict_follower_selection/readme/DESCRIPTION.rst
  mail_restrict_follower_selection/static/description/icon.png
  mail_restrict_follower_selection/static/description/index.html
  mail_restrict_follower_selection/tests/__init__.py
  mail_restrict_follower_selection/tests/test_mail_restrict_follower_selection.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mail_restrict_follower_selection/odoo/addons/mail_restrict_follower_selection
  setup/mail_restrict_follower_selection/setup.py
Labels: 14.0

#602 Syncing from upstream OCA/social (13.0)
  README.md
  mail_tracking_mass_mailing/__manifest__.py
  mail_tracking_mass_mailing/models/mail_mail.py
  mail_tracking_mass_mailing/models/mailing_trace.py
  mail_tracking_mass_mailing/tests/test_mass_mailing.py
Labels: 13.0

#603 Syncing from upstream OCA/social (14.0)
  README.md
  mail_tracking_mass_mailing/__manifest__.py
  mail_tracking_mass_mailing/models/mail_mail.py
  mail_tracking_mass_mailing/models/mailing_trace.py
  mail_tracking_mass_mailing/tests/test_mass_mailing.py
Labels: 14.0

#604 Syncing from upstream OCA/social (15.0)
  README.md
  mail_autosubscribe/README.rst
  mail_autosubscribe/__init__.py
  mail_autosubscribe/__manifest__.py
  mail_autosubscribe/i18n/ca.po
  mail_autosubscribe/i18n/mail_autosubscribe.pot
  mail_autosubscribe/models/__init__.py
  mail_autosubscribe/models/mail_autosubscribe.py
  mail_autosubscribe/models/mail_template.py
  mail_autosubscribe/models/mail_thread.py
  mail_autosubscribe/models/models.py
  mail_autosubscribe/models/res_partner.py
  mail_autosubscribe/readme/CONFIGURE.rst
  mail_autosubscribe/readme/CONTRIBUTORS.rst
  mail_autosubscribe/readme/DESCRIPTION.rst
  mail_autosubscribe/readme/ROADMAP.rst
  mail_autosubscribe/security/ir.model.access.csv
  mail_autosubscribe/static/description/icon.png
  mail_autosubscribe/static/description/index.html
  mail_autosubscribe/tests/__init__.py
  mail_autosubscribe/tests/models/__init__.py
  mail_autosubscribe/tests/models/fake_order.py
  mail_autosubscribe/tests/test_mail_autosubscribe.py
  mail_autosubscribe/views/mail_autosubscribe.xml
  mail_autosubscribe/views/mail_template.xml
  mail_autosubscribe/views/res_partner.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mail_autosubscribe/odoo/addons/mail_autosubscribe
  setup/mail_autosubscribe/setup.py
Labels: 15.0

#605 Syncing from upstream OCA/social (12.0)
  README.md
  mail_drop_target/__manifest__.py
  mail_inline_css/__manifest__.py
  mail_inline_css/models/mail_template.py
  requirements.txt
  setup/mail_drop_target/setup.py
  test-requirements.txt
Labels: 12.0

#606 Syncing from upstream OCA/social (13.0)
  README.md
  mail_activity_team/__manifest__.py
  mail_activity_team/i18n/fr.po
  mail_activity_team/i18n/it.po
  mail_activity_team/i18n/mail_activity_team.pot
  mail_activity_team/models/__init__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/models/mail_activity_type.py
  mail_activity_team/models/res_users.py
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/mail_activity_type.xml
Labels: 13.0

#608 [BUG] mail_improved_tracking_valuee: bug on view
  mail_improved_tracking_value/views/mail_tracking_value.xml
Labels: 13.0.project_ms_592

#609 Syncing from upstream OCA/social (14.0)
  README.md
  mail_debrand/__manifest__.py
  mail_debrand/models/mail_render_mixin.py
Labels: 14.0
