Repository brain-tec/social, pull requests merged in 2022-02, with the labels that each got.

#549 Syncing from upstream OCA/social (14.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/website_mass_mailing_name/odoo/addons/website_mass_mailing_name
  setup/website_mass_mailing_name/setup.py
  website_mass_mailing_name/README.rst
  website_mass_mailing_name/__init__.py
  website_mass_mailing_name/__manifest__.py
  website_mass_mailing_name/controllers/__init__.py
  website_mass_mailing_name/controllers/main.py
  website_mass_mailing_name/i18n/de.po
  website_mass_mailing_name/i18n/es.po
  website_mass_mailing_name/i18n/fr.po
  website_mass_mailing_name/i18n/hr.po
  website_mass_mailing_name/i18n/pt.po
  website_mass_mailing_name/i18n/sl.po
  website_mass_mailing_name/i18n/website_mass_mailing_name.pot
  website_mass_mailing_name/readme/CONTRIBUTORS.rst
  website_mass_mailing_name/readme/DESCRIPTION.rst
  website_mass_mailing_name/readme/USAGE.rst
  website_mass_mailing_name/static/description/icon.png
  website_mass_mailing_name/static/description/index.html
  website_mass_mailing_name/static/src/css/website_mass_mailing_name.scss
  website_mass_mailing_name/static/src/js/admin_and_public_tour.js
  website_mass_mailing_name/static/src/js/website_mass_mailing_name.js
  website_mass_mailing_name/templates/assets.xml
  website_mass_mailing_name/templates/snippets.xml
  website_mass_mailing_name/tests/__init__.py
  website_mass_mailing_name/tests/snippet_test_page.xml
  website_mass_mailing_name/tests/test_ui.py
Labels: 14.0

#550 Manual syncing from upstream OCA/social (14.0)
  mail_optional_follower_notification/i18n/es.po
Labels: 14.0

#551 Syncing from upstream OCA/social (14.0)
  README.md
  mass_mailing_subscription_email/__init__.py
  mass_mailing_subscription_email/__manifest__.py
  mass_mailing_subscription_email/controllers/__init__.py
  mass_mailing_subscription_email/controllers/main.py
  mass_mailing_subscription_email/i18n/mass_mailing_subscription_email.pot
  mass_mailing_subscription_email/models/__init__.py
  mass_mailing_subscription_email/models/mail_mail.py
  mass_mailing_subscription_email/models/mailing_contact_subscription.py
  mass_mailing_subscription_email/tests/__init__.py
  mass_mailing_subscription_email/tests/test_subscription_email.py
  mass_mailing_subscription_email/tests/test_unsubscribe_from_list.py
Labels: 14.0

#552 Syncing from upstream OCA/social (14.0)
  README.md
  mass_mailing_company_newsletter/__manifest__.py
  mass_mailing_company_newsletter/models/res_partner.py
Labels: 14.0

#554 Syncing from upstream OCA/social (13.0)
  README.md
  mail_template_multi_attachment/README.rst
  mail_template_multi_attachment/__init__.py
  mail_template_multi_attachment/__manifest__.py
  mail_template_multi_attachment/i18n/mail_template_multi_attachment.pot
  mail_template_multi_attachment/models/__init__.py
  mail_template_multi_attachment/models/mail_template.py
  mail_template_multi_attachment/models/mail_template_report.py
  mail_template_multi_attachment/readme/CONFIGURE.rst
  mail_template_multi_attachment/readme/CONTRIBUTORS.rst
  mail_template_multi_attachment/readme/DESCRIPTION.rst
  mail_template_multi_attachment/readme/USAGE.rst
  mail_template_multi_attachment/security/mail_template_report.xml
  mail_template_multi_attachment/static/description/icon.png
  mail_template_multi_attachment/static/description/index.html
  mail_template_multi_attachment/tests/__init__.py
  mail_template_multi_attachment/tests/test_mail_template.py
  mail_template_multi_attachment/views/mail_template.xml
  mail_template_multi_attachment/views/mail_template_report.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mail_template_multi_attachment/odoo/addons/mail_template_multi_attachment
  setup/mail_template_multi_attachment/setup.py
Labels: 13.0

#555 Syncing from upstream OCA/social (15.0)
  README.md
  mail_preview_base/README.rst
  mail_preview_base/__init__.py
  mail_preview_base/__manifest__.py
  mail_preview_base/i18n/mail_preview_base.pot
  mail_preview_base/readme/CONTRIBUTORS.rst
  mail_preview_base/readme/DESCRIPTION.rst
  mail_preview_base/readme/USAGE.rst
  mail_preview_base/static/description/icon.png
  mail_preview_base/static/description/index.html
  mail_preview_base/static/src/js/preview.js
  mail_preview_base/static/src/scss/preview.scss
  mail_preview_base/static/src/xml/preview.xml
  mail_preview_base/views/ir_attachment_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mail_preview_base/odoo/addons/mail_preview_base
  setup/mail_preview_base/setup.py
Labels: 15.0

#556 Syncing from upstream OCA/social (14.0)
  README.md
  mass_mailing_subscription_email/__manifest__.py
  mass_mailing_subscription_email/controllers/main.py
Labels: 14.0

#558 Syncing from upstream OCA/social (13.0)
  mail_debrand/i18n/nl.po
Labels: 13.0
