Repository brain-tec/social, pull requests merged in 2022-04, with the labels that each got.

#580 Syncing from upstream OCA/social (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0

#581 Syncing from upstream OCA/social (13.0)
  README.md
  mail_tracking_mailgun/__manifest__.py
  mail_tracking_mailgun/wizards/res_config_settings.py
  mass_mailing_partner/__manifest__.py
  mass_mailing_partner/models/res_partner.py
Labels: 13.0

#582 Syncing from upstream OCA/social (14.0)
  README.md
  mass_mailing_partner/__manifest__.py
  mass_mailing_partner/models/res_partner.py
  mass_mailing_partner/views/res_partner_view.xml
Labels: 14.0

#583 13.0 mig mail improved tracking value/13.0
  mail_improved_tracking_value/README.rst
  mail_improved_tracking_value/__init__.py
  mail_improved_tracking_value/__manifest__.py
  mail_improved_tracking_value/i18n/fr.po
  mail_improved_tracking_value/i18n/mail_improved_tracking_value.pot
  mail_improved_tracking_value/models/__init__.py
  mail_improved_tracking_value/models/mail_tracking_value.py
  mail_improved_tracking_value/static/description/icon.png
  mail_improved_tracking_value/tests/__init__.py
  mail_improved_tracking_value/tests/test_improved_tracking_value.py
  mail_improved_tracking_value/views/mail_tracking_value.xml
Labels: 13.0

#584 [t127838] Migrate module mail_improved_tracking_value
  README.md
  mail_improved_tracking_value/__manifest__.py
  mail_improved_tracking_value/models/__init__.py
  mail_improved_tracking_value/models/mail_tracking_value.py
  mail_improved_tracking_value/tests/test_improved_tracking_value.py
  mail_improved_tracking_value/views/mail_tracking_value.xml
  main.py
  setup/mail_improved_tracking_value/odoo/addons/mail_improved_tracking_value
  setup/mail_improved_tracking_value/setup.py
Labels: 13.0.project_ms_592

#585 Syncing from upstream OCA/social (15.0)
  README.md
  mail_debrand/__manifest__.py
  mail_debrand/models/mail_render_mixin.py
Labels: 15.0

#586 Syncing from upstream OCA/social (13.0)
  README.md
  mail_activity_board/README.rst
  mail_activity_board/__manifest__.py
  mail_activity_board/i18n/es.po
  mail_activity_board/i18n/fr.po
  mail_activity_board/i18n/fr_BE.po
  mail_activity_board/i18n/hu.po
  mail_activity_board/i18n/it.po
  mail_activity_board/i18n/mail_activity_board.pot
  mail_activity_board/models/mail_activity.py
  mail_activity_board/readme/CONTRIBUTORS.rst
  mail_activity_board/static/description/index.html
  mail_activity_board/tests/test_mail_activity_board.py
  mail_activity_board/views/mail_activity_view.xml
  mail_activity_team/__manifest__.py
  mail_activity_team/i18n/mail_activity_team.pot
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_mixin.py
  mail_activity_team/models/res_users.py
  mail_activity_team/static/src/js/systray.js
  mail_activity_team/static/src/xml/systray.xml
  mail_activity_team/tests/test_mail_activity_team.py
  mail_activity_team/views/assets_backend.xml
  mail_activity_team/views/mail_activity_views.xml
  mail_restrict_follower_selection/__manifest__.py
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
  mail_restrict_follower_selection/tests/test_mail_restrict_follower_selection.py
Labels: 13.0

#587 Syncing from upstream OCA/social (14.0)
  README.md
  mail_activity_board/README.rst
  mail_activity_board/__manifest__.py
  mail_activity_board/i18n/mail_activity_board.pot
  mail_activity_board/models/mail_activity.py
  mail_activity_board/readme/CONTRIBUTORS.rst
  mail_activity_board/static/description/index.html
  mail_activity_board/tests/test_mail_activity_board.py
  mail_activity_board/views/mail_activity_view.xml
Labels: 14.0

#588 Syncing from upstream OCA/social (13.0)
  mail_activity_team/i18n/fr.po
  mail_activity_team/i18n/it.po
Labels: 13.0

#589 Syncing from upstream OCA/social (14.0)
  mail_activity_board/i18n/es.po
  mail_activity_board/i18n/fr_BE.po
Labels: 14.0

#590 Syncing from upstream OCA/social (15.0)
  README.md
  mail_activity_team/README.rst
  mail_activity_team/__manifest__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_team.py
  mail_activity_team/models/res_users.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/static/description/index.html
  mail_activity_team/tests/test_mail_activity_team.py
  mail_debrand/README.rst
  mail_debrand/__manifest__.py
  mail_debrand/readme/CONTRIBUTORS.rst
  mail_debrand/static/description/index.html
  mail_show_follower/__manifest__.py
  mail_show_follower/models/mail_mail.py
Labels: 15.0

#591 Syncing from upstream OCA/social (14.0)
  README.md
  mail_activity_team/README.rst
  mail_activity_team/__manifest__.py
  mail_activity_team/models/mail_activity.py
  mail_activity_team/models/mail_activity_team.py
  mail_activity_team/models/res_users.py
  mail_activity_team/readme/CONTRIBUTORS.rst
  mail_activity_team/static/description/index.html
  mail_activity_team/tests/test_mail_activity_team.py
  mail_debrand/README.rst
  mail_debrand/__manifest__.py
  mail_debrand/models/mail_render_mixin.py
  mail_debrand/readme/CONTRIBUTORS.rst
  mail_debrand/static/description/index.html
Labels: 14.0

#592 Syncing from upstream OCA/social (13.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
Labels: 13.0

#593 Syncing from upstream OCA/social (14.0)
  README.md
  mail_show_follower/README.rst
  mail_show_follower/__manifest__.py
  mail_show_follower/i18n/fr.po
  mail_show_follower/i18n/mail_show_follower.pot
  mail_show_follower/models/mail_mail.py
  mail_show_follower/models/res_company.py
  mail_show_follower/models/res_config_settings.py
  mail_show_follower/readme/CONFIGURE.rst
  mail_show_follower/readme/CONTRIBUTORS.rst
  mail_show_follower/static/description/index.html
  mail_show_follower/views/res_config_settings.xml
Labels: 14.0

#594 Syncing from upstream OCA/social (14.0)
  mass_mailing_subscription_email/i18n/pt.po
Labels: 14.0

#595 Syncing from upstream OCA/social (14.0)
  mass_mailing_subscription_email/i18n/pt.po
Labels: 14.0

#596 Syncing from upstream OCA/social (15.0)
  README.md
  base_search_mail_content/__manifest__.py
  base_search_mail_content/models/mail_thread.py
Labels: 15.0

#597 Syncing from upstream OCA/social (14.0)
  README.md
  email_template_qweb/__manifest__.py
  email_template_qweb/models/mail_template.py
  mail_preview_audio/README.rst
  mail_preview_audio/__init__.py
  mail_preview_audio/__manifest__.py
  mail_preview_audio/i18n/mail_preview_audio.pot
  mail_preview_audio/readme/CONTRIBUTORS.rst
  mail_preview_audio/readme/DESCRIPTION.rst
  mail_preview_audio/static/description/icon.png
  mail_preview_audio/static/description/index.html
  mail_preview_audio/static/src/js/preview.js
  mail_preview_audio/static/src/xml/preview.xml
  mail_preview_audio/template/assets.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/mail_preview_audio/odoo/addons/mail_preview_audio
  setup/mail_preview_audio/setup.py
Labels: 14.0

#598 Syncing from upstream OCA/social (14.0)
  README.md
  mail_allow_portal_internal_note/__manifest__.py
  mail_allow_portal_internal_note/controllers/mail.py
  mail_allow_portal_internal_note/i18n/mail_allow_portal_internal_note.pot
  mail_allow_portal_internal_note/models/res_users.py
  mail_allow_portal_internal_note/static/src/js/composer.js
  mail_allow_portal_internal_note/static/src/xml/mail_portal_template.xml
  mail_allow_portal_internal_note/views/assets.xml
Labels: 14.0

#599 Syncing from upstream OCA/social (15.0)
  README.md
  mail_activity_team/__manifest__.py
  mail_activity_team/i18n/fr.po
  mail_activity_team/i18n/it.po
  mail_activity_team/i18n/mail_activity_team.pot
  mail_activity_team/views/mail_activity_team_views.xml
Labels: 15.0
