Repository brain-tec/social, pull requests merged in 2024-08, with the labels that each got.

#1049 Syncing from upstream OCA/social (17.0)
  README.md
  base_search_mail_content/README.rst
  base_search_mail_content/__manifest__.py
  base_search_mail_content/models/mail_thread.py
  base_search_mail_content/readme/ROADMAP.md
  base_search_mail_content/static/description/index.html
Labels: 17.0

#1050 [t151230] Merge OCA module mail_send_confirmation
  README.md
  mail_send_confirmation/README.rst
  mail_send_confirmation/__init__.py
  mail_send_confirmation/__manifest__.py
  mail_send_confirmation/readme/CONTRIBUTORS.rst
  mail_send_confirmation/readme/DESCRIPTION.rst
  mail_send_confirmation/static/description/icon.png
  mail_send_confirmation/static/description/index.html
  mail_send_confirmation/static/src/components/composer/composer.esm.js
  setup/mail_send_confirmation/odoo/addons/mail_send_confirmation
  setup/mail_send_confirmation/setup.py
Labels: 15.0.project_gr_578

#1052 Syncing from upstream OCA/social (14.0)
  README.md
  mail_restrict_follower_selection/README.rst
  mail_restrict_follower_selection/__init__.py
  mail_restrict_follower_selection/__manifest__.py
  mail_restrict_follower_selection/models/mail_followers.py
  mail_restrict_follower_selection/models/mail_thread.py
  mail_restrict_follower_selection/models/mail_wizard_invite.py
  mail_restrict_follower_selection/static/description/index.html
  mail_restrict_follower_selection/tests/test_mail_restrict_follower_selection.py
  mail_restrict_follower_selection/utils.py
Labels: 14.0

#1053 Syncing from upstream OCA/social (15.0)
  README.md
  mail_drop_target/README.rst
  mail_drop_target/__manifest__.py
  mail_drop_target/static/description/index.html
  mail_drop_target/static/src/js/mail_drop_target.esm.js
Labels: 15.0

#1054 Syncing from upstream OCA/social (16.0)
  mass_mailing_partner/i18n/hr.po
Labels: 16.0
